### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by zvezdochiot** [ZyperPL/ImageMatrixTransform#1]
Hi @ZyperPL

https://github.com/ZyperPL/ImageMatrixTransform/blob/6a906d35e3b03c9b6ae26a7e21fba485007aa6a3/makefile#L4

Works too with `-std=c++11`.

https://github.com/ZyperPL/ImageMatrixTransform/blob/6a906d35e3b03c9b6ae26a7e21fba485007aa6a3/makefile#L10

`-lglfw` not needed.

**Comment by ZyperPL** [comment]
Hi, 
Thanks for your comment. 
Actually all of the libraries are not needed, because they are left-overs from another project. 
This repository was just a toy-project back when I was studying, but I fixed it anyway. ;)
Cheers!
